site_name: ChemMatData
nav:
  - Introduction: index.md
  - Datasets: datasets.md
  - Getting Started:
    - Installation: installation.md
    - First steps: first_steps.md
  - Command Line Interface:
    - List Available Datasets: cli_list.md
    - Show Dataset Metadata: cli_info.md
    - Download Dataset: cli_download.md
    - Local Configuration File: cli_config.md
    - Local File Cache: cli_cache.md
  - Programming Interface:
    - Loading Datasets: api_datasets.md
    - Streaming Datasets: api_streaming_datasets.md
    - Graph Representation: graph_representation.md
    - Processing New Graphs: processing_graphs.md
    - Custom Pre-Processing: custom_pre_processing.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: material
  logo: assets/logo.png
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.expand
